In [1]:
# Import required libaries
import pandas as pd
import numpy as np
import warnings

In [2]:
# loading in the (anonymized) data
df = pd.read_csv("P1_2425_C1_Answers_Anon.csv")

# Shape of data
print("Shape of data:\n",df.shape)
print("Number of students:\n",df.shape[0])

#Ignore warnings
warnings.filterwarnings('ignore')

# First 5 rows of whole data set (including exam questions + survey questions)
df.head()

Shape of data:
 (184, 42)
Number of students:
 184

,Student number,1,2,5,6,7,8,9,10,11,...,37,38,39,40,49,50,51,52,53,54
0,0,A,A,B,A,a,b,A,A,c,...,A,B,B,B,A,A,B,EFC,E,C
1,1,A,A,B,b,B,A,A,A,B,...,b,B,B,B,A,A,B,DABCEF,E,D
2,2,A,A,B,A,a,b,A,A,a,...,A,a,B,a,A,A,B,E,E,D
3,3,A,A,B,A,B,A,A,A,c,...,A,a,B,a,A,A,C,ABE,E,B
4,4,A,A,B,A,B,A,A,A,c,...,A,B,B,B,A,D,E,ADE,E,B

In [3]:

# Stating survey answers

questions = {'49':' I Consent',
             '50':'From 1 to 5, how do you evaluate your level of programming before taking the Programming 2 course?',
             '51':' From 1 to 5, how do you evaluate your current level of programming after taking the Programming 2 course?',
             '52':'Which of the following learning strategies did you use during the Programming 2 course?\nA: Revisiting the lecture slides\nB: Doing project practice extra exercises (at the end of each assignment)\nC: Reading the recommended literature\nD: Doing project lovelace exercises\nE: Attending to/watching the lectures\nF: Attending the practice sessions (on Wednesdays)',
             '53':'From 1 to 5, how often did you attend the lectures (or watch the lecture recording before the workgroups)?',
             '54':'From 1 to 5, how often did you attend the practice sessions?'}
survey_answers = df[['49','50','51','52','53','54']]
survey_answers_learning_strategies = df[['49','52','53','54']]
# Printing questions for clarity (A:1 - E:5)
for number,question in questions.items():
    print(f"question {number}:\n{question}\n")

# Head of survey data frame
survey_answers.head()

question 49:
 I Consent

question 50:
From 1 to 5, how do you evaluate your level of programming before taking the Programming 2 course?

question 51:
 From 1 to 5, how do you evaluate your current level of programming after taking the Programming 2 course?

question 52:
Which of the following learning strategies did you use during the Programming 2 course?
A: Revisiting the lecture slides
B: Doing project practice extra exercises (at the end of each assignment)
C: Reading the recommended literature
D: Doing project lovelace exercises
E: Attending to/watching the lectures
F: Attending the practice sessions (on Wednesdays)

question 53:
From 1 to 5, how often did you attend the lectures (or watch the lecture recording before the workgroups)?

question 54:
From 1 to 5, how often did you attend the practice sessions?

  49 50 51      52 53 54
0  A  A  B     EFC  E  C
1  A  A  B  DABCEF  E  D
2  A  A  B       E  E  D
3  A  A  C     ABE  E  B
4  A  D  E     ADE  E  B

In [4]:
print("Shape:\n",survey_answers_learning_strategies.shape)
survey_answers_learning_strategies.head()

Shape:
 (184, 4)

  49      52 53 54
0  A     EFC  E  C
1  A  DABCEF  E  D
2  A       E  E  D
3  A     ABE  E  B
4  A     ADE  E  B

In [5]:
# Keep only answers where student gave consent and with no NaN
survey_answers_learning_strategies = survey_answers_learning_strategies[survey_answers_learning_strategies["49"]=='A']
survey_answers_learning_strategies = survey_answers_learning_strategies.dropna()
print("Shape:",survey_answers_learning_strategies.shape)
print("Number of people who gave consent:",survey_answers_learning_strategies.shape[0])
print(f"Difference with total: {survey_answers.shape[0] - survey_answers_learning_strategies.shape[0]}, Percentage: {((survey_answers_learning_strategies.shape[0] / survey_answers.shape[0]) *100):.2f}%")
# Preprocessing
categorical_translation = {"A":1,
                           "B":2,
                           "C":3,
                           "D":4,
                           "E":5}

# Question 53 and 54 will be translated to numerical values
survey_answers_learning_strategies["53"] = survey_answers_learning_strategies["53"].replace(["A","B","C","D","E",],[1,2,3,4,5])
survey_answers_learning_strategies["54"] = survey_answers_learning_strategies["54"].replace(["A","B","C","D","E",],[1,2,3,4,5])
# Question 52 needs to be represented as 6 distinct columns to indicate if strategy was present (0=no 1=yes)
print("\nDifferent occurences question 52:",len(survey_answers_learning_strategies["52"].unique()))

answers_52 = ["A","B","C","D","E","F"]

results = []
for answer in answers_52:
    # Empry array of zeroes
    result = np.zeros(len(survey_answers_learning_strategies["52"]))

    # Ones if the choice (A - F) is present in the answer
    ones = [1  if answer in x else 0 for x in survey_answers_learning_strategies["52"]]
    results.append(ones)
    
results = np.array(results).T # needs to have shape of (booleans(0 or 1), survey_answers) (128,6)
print(np.array(results).shape)

temp_df = pd.DataFrame((results),columns=answers_52)
temp_df.head()

Shape: (128, 4)
Number of people who gave consent: 128
Difference with total: 56, Percentage: 69.57%

Different occurences question 52: 54
(128, 6)

   A  B  C  D  E  F
0  0  0  1  0  1  1
1  1  1  1  1  1  1
2  0  0  0  0  1  0
3  1  1  0  0  1  0
4  1  0  0  1  1  0